### ISSUE TITLE
Plugin.video.pulsar-0.4.7 -> 0.5.0

### ISSUE THREAD

**Issue by raspdealer** [prilly/repository.kodiunderground#1]
Hi,

Thanks for your repo. It works fine on OSMC with CURL version 7.38 which create a 07:42:46 T:1751364640 ERROR: CCurlFile::FillBuffer - Failed: SSL connect error(35) on others SSL repo.

BUT 

On your [svn](http://kodi.speedbox.me/svn_kodi/trunk/plugin.video.pulsar/), you have the version 0.5.0 of Pulsar addon but your [addons.xml ](http://kodi.speedbox.me/svn_kodi/trunk/addons.xml) is binding to the old version 0.4.7. So we get a 404 when you try to install it.
`Line 87 : <addon id="plugin.video.pulsar" name="Pulsar" version="0.4.7" provider-name="steeve">`

Can you please regenerate/update your xml/repo ?

Thanks

**Comment by prilly** [comment]
its updated now, i forgot some files in the last commit.

**Comment by raspdealer** [comment]
Thanks I'll try this !

**Comment by prilly** [comment]
Give it a couple of hours, updating the addons.xml with new version of pulsar 
generates huge amount of traffic, 

It tends to calm down after some hours



Onsdag 8. april 2015 03.04.36 skrev Raspdealer:

**Comment by raspdealer** [comment]
It's ok thanks
